version: "3.8"
services:
  y-main:
    container_name: y-main
    build:
      context: ./main/
      args:
        - CONFIG_FILE=dev.yaml
    restart: always
    env_file:
      - ./main/dev.env
    ports:
      - "5001:5001"
    networks:
      - ystudent
  y-auth:
    container_name: y-auth
    build:
      context: ./auth/
      args:
        - CONFIG_FILE=dev.yaml
    restart: always
    env_file:
      - ./auth/dev.env
    ports:
      - "5000:5000"
    networks:
      - ystudent
  y-chat:
    container_name: y-chat
    build: ./chat/
    restart: always
    env_file:
      - ./chat/.env
    ports:
      - "3000:3000"
    networks:
      - ystudent

networks:
  ystudent:
    external: true
