version: "3.8"

services:
  # db:
  #   image: postgres
  #   restart: always
  #   container_name: "auth-db"
  #   env_file:
  #     - ./postgres.env
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - backend
  app:
    container_name: "auth"
    build: .
    restart: always
    environment:
      CONFIG_PATH: "/prod.yaml"
    ports:
      - "5000:5000"
    depends_on:
      - db
#     networks:
#       - backend
#
# networks:
#   backend:
#     driver: bridge
