env: "local" # local, dev, prod
context_timeout: 5s
http:
  port: "5000"
  host: "localhost"
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 5s
postgres: # может быть любая бд
  username: "ystudent"
  password: "password"
  host: "localhost"
  port: "5432"
  database: "auth"
jwt:
  access_token_secret: "my-big-hard-secret123"
  refresh_token_secret: "my-big-hard-secret123"
  access_expires_at: 15m
  refresh_expires_at: 720h
admin:
  login: "vicdevcode"
  password: "123123123"
fill_database: false
