env: "prod" # local, dev, prod
context_timeout: 5s
http:
  port: "5000"
  host: "auth"
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 5s
jwt:
  access_token_secret: "access_secret"
  refresh_token_secret: "refresh_secret"
  access_expires_at: 15m
  refresh_expires_at: 720h
admin:
  login: "vicdevcode"
  password: "123123123"
fill_database: true
rabbitmq:
  username: "ystudent"
  password: "123123"
  host: "localhost"
  port: "5672"
  exchange_name: "ystudent"
  queue_name: "auth"
  topics: ["auth.*", "auth.*.*"]
sqlite:
  path: "auth.db"
postgres:
  username: "ystudent"
  password: "password"
  host: "auth-db"
  port: "5432"
  database: "auth"
