# for local development

env: "local"
context_timeout: 5s
http:
  port: "5000"
  host: "localhost"
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 5s
postgres:
  username: "ystudent"
  password: "123123123"
  host: "localhost"
  port: "5432"
  database: "auth"
jwt:
  access_token_secret: "my-big-hard-secret123"
  refresh_token_secret: "my-big-hard-secret123"
  access_expires_at: 15m
  refresh_expires_at: 720h
admin:
  login: "vicdevcode"
  password: "123123123"
fill_database: false
rabbitmq:
  username: "ystudent"
  password: "123123"
  host: "localhost"
  port: "5672"
  exchange_name: "ystudent"
  queue_name: "auth"
  topics: ["chat.*", "chat.*.*"]

# for development

env: "dev"
context_timeout: 5s
http:
  port: "5000"
  host: "y-auth"
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 5s
postgres: # может быть любая бд
  username: "ystudent"
  password: "123123123"
  host: "y-pgsql"
  port: "5432"
  database: "auth"
jwt:
  access_token_secret: "my-big-hard-secret123"
  refresh_token_secret: "my-big-hard-secret123"
  access_expires_at: 15m
  refresh_expires_at: 720h
admin:
  login: "vicdevcode"
  password: "123123123"
fill_database: false
rabbitmq:
  username: "ystudent"
  password: "123123"
  host: "y-rabbitmq"
  port: "5672"
  exchange_name: "ystudent"
  queue_name: "auth"
  topics: ["chat.*", "chat.*.*"]

# for production

env: "prod"
context_timeout: 5s
http:
  port: "5000"
  host: "y-auth"
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 5s
postgres:
  username: "ystudent"
  password: "password"
  host: "y-pgsql"
  port: "5432"
  database: "auth"
jwt:
  access_token_secret: "ystudentaccesssecrettoken1258jgid91248"
  refresh_token_secret: "ystudenttokenrefreshaccesssecret4u123"
  access_expires_at: 15m
  refresh_expires_at: 720h
admin:
  login: "ysadministrator"
  password: "hardpassword"
fill_database: true
rabbitmq:
  username: "ystudent"
  password: "123123"
  host: "y-rabbitmq"
  port: "5672"
  exchange_name: "ystudent"
  queue_name: "auth"
  topics: ["auth.*", "auth.*.*"]
